# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case_type',
            old_name='Status',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='irm_ethinicity',
            old_name='Ethnicity',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='irm_location',
            old_name='Location',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='irm_title',
            old_name='Title',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='marital_status',
            old_name='status',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='panel_recommendations',
            old_name='Recommendation',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='panel_role',
            old_name='Role',
            new_name='types',
        ),
        migrations.RenameField(
            model_name='report_status',
            old_name='Status',
            new_name='types',
        ),
    ]
