# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0002_auto_20160406_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(help_text='F Name', max_length=100)),
                ('Last_Name', models.CharField(help_text='L Name', max_length=100)),
                ('Ethnicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_Ethinicity')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_Location')),
            ],
        ),
    ]
