# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0003_test_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(help_text='Type of Agency', max_length=100, verbose_name='Agency Type')),
            ],
        ),
        migrations.CreateModel(
            name='IRM_Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgencyName', models.CharField(help_text='Agency Name', max_length=100)),
                ('AgencyFullName', models.CharField(help_text='Agency Full Name', max_length=100)),
                ('Notes', models.TextField(help_text='Notes', max_length=2000)),
                ('To_Delete', models.BooleanField(default=False)),
                ('Agency_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.Agency_Type')),
            ],
        ),
        migrations.AlterField(
            model_name='case_type',
            name='types',
            field=models.CharField(max_length=20, verbose_name='Case Type'),
        ),
        migrations.AlterField(
            model_name='irm_ethinicity',
            name='types',
            field=models.CharField(help_text='Ethnicity', max_length=100, verbose_name='Ethnicity'),
        ),
        migrations.AlterField(
            model_name='irm_location',
            name='types',
            field=models.CharField(help_text='Location', max_length=100, verbose_name='IRM Office Location'),
        ),
        migrations.AlterField(
            model_name='irm_title',
            name='types',
            field=models.CharField(help_text='Title', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='marital_status',
            name='types',
            field=models.CharField(max_length=20, verbose_name='Marital Status'),
        ),
        migrations.AlterField(
            model_name='panel_recommendations',
            name='types',
            field=models.CharField(help_text='Placeholder', max_length=200, verbose_name='Panel Recommendations'),
        ),
        migrations.AlterField(
            model_name='panel_role',
            name='types',
            field=models.CharField(max_length=50, verbose_name='Panel Role'),
        ),
        migrations.AlterField(
            model_name='report_status',
            name='types',
            field=models.CharField(max_length=20, verbose_name='Report Status'),
        ),
        migrations.AlterField(
            model_name='test_person',
            name='First_Name',
            field=models.CharField(help_text='F Name', max_length=100, verbose_name='Sample person first name'),
        ),
        migrations.AddField(
            model_name='irm_agency',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_Location'),
        ),
    ]
