# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0005_test_person_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRM_Agency_Admin_Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(help_text='First name of Agency Admin', max_length=100)),
                ('Surname', models.CharField(help_text='Surname of Agency Admin', max_length=100)),
                ('Position', models.CharField(help_text='Position(Designation) in the Agency', max_length=100)),
                ('Address_Line_1', models.CharField(help_text='Placeholder', max_length=200)),
                ('Address_Line_2', models.CharField(blank=True, help_text='Placeholder', max_length=200, null=True)),
                ('Address_Line_3', models.CharField(blank=True, help_text='Placeholder', max_length=200, null=True)),
                ('Address_Line_4', models.CharField(blank=True, help_text='Placeholder', max_length=200, null=True)),
                ('Town', models.CharField(blank=True, help_text='Town', max_length=200, null=True)),
                ('County', models.CharField(blank=True, help_text='County', max_length=200, null=True)),
                ('Postcode', models.CharField(help_text='UK Postcode', max_length=200)),
                ('Phone', models.CharField(help_text='Phone Number', max_length=200)),
                ('Mobile', models.CharField(help_text='Mobile Number', max_length=200)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Fax', models.IntegerField(help_text='Mobile Number')),
                ('Role', models.CharField(choices=[('Admin Contact', 'Admin Contact'), ('Decision Maker', 'Decision Maker')], help_text='Role Type', max_length=50)),
                ('Notes', models.CharField(blank=True, help_text='Short Notes about Agency', max_length=500, null=True)),
                ('AgencyID_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_Agency')),
                ('Title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_Title')),
            ],
        ),
    ]
