# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0008_auto_20160407_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='irm_agency',
            name='Created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='irm_agency',
            name='Modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='irm_agency',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 19, 46, 49, 731460, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irm_agency',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 19, 46, 52, 982383, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='irm_agency',
            name='Agency_Name',
            field=models.CharField(default='Initial_Name_Ignore', help_text='Agency Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='irm_agency',
            name='Notes',
            field=models.TextField(blank=True, help_text='Notes', max_length=2000, null=True),
        ),
    ]
