# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0010_auto_20160407_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irm_agency',
            name='Created_by',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='irm_agency_admin_contact',
            name='Fax',
            field=models.IntegerField(blank=True, help_text='Fax Number', null=True),
        ),
    ]
