# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0011_auto_20160410_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='irm_agency_admin_contact',
            name='Created_by',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='irm_agency_admin_contact',
            name='Modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='irm_agency_admin_contact',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 19, 34, 3, 483448, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='irm_agency_admin_contact',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 19, 34, 8, 793409, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
