# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-10 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0012_auto_20160410_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irm_agency_admin_contact',
            name='AgencyID_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_Agency', verbose_name='Agency'),
        ),
    ]
