# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0014_auto_20160411_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irm_agency_admin_contact',
            name='Created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
