# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0015_auto_20160411_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRM_PanelContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('Participant_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Position', models.CharField(blank=True, max_length=50, null=True)),
                ('Home_Address_Line_1', models.CharField(max_length=100)),
                ('Home_Address_Line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('Home_Address_Line_3', models.CharField(blank=True, max_length=100, null=True)),
                ('Home_Address_Line_4', models.CharField(blank=True, max_length=100, null=True)),
                ('Home_Town', models.CharField(max_length=100)),
                ('Home_County', models.CharField(blank=True, max_length=100, null=True)),
                ('Home_Postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('Home_Phone', models.CharField(blank=True, max_length=40, null=True)),
                ('Work_Address_Line_1', models.CharField(max_length=100)),
                ('Work_Address_Line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('Work_Address_Line_3', models.CharField(blank=True, max_length=100, null=True)),
                ('Work_Address_Line_4', models.CharField(blank=True, max_length=100, null=True)),
                ('Work_Town', models.CharField(max_length=100)),
                ('Work_County', models.CharField(blank=True, max_length=100, null=True)),
                ('Work_Postcode', models.CharField(max_length=100)),
                ('Work_Phone', models.CharField(blank=True, max_length=40, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=40, null=True)),
                ('Email', models.EmailField(blank=True, max_length=40, null=True)),
                ('Fax', models.CharField(blank=True, max_length=40, null=True)),
                ('Appointment_Date', models.DateField()),
                ('To_Delete', models.BooleanField(default=False)),
                ('Availability', models.CharField(blank=True, max_length=100, null=True)),
                ('Status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
                ('Notes', models.TextField(blank=True, max_length=200, null=True)),
                ('Modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('Created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('Ethnicity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_Ethinicity')),
                ('Four_IRMLocationID_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irm_panelcontact_Fourth_Location', to='IRM.IRM_Location')),
                ('Panel_Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.Panel_Role')),
                ('Principal_IRMLocationID_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irm_panelcontact_Principal_Location', to='IRM.IRM_Location')),
                ('Three_IRMLocationID_FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irm_panelcontact_Third_Location', to='IRM.IRM_Location')),
                ('Title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_Title')),
                ('Two_IRMLocationID_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irm_panelcontact_Secondary_Location', to='IRM.IRM_Location')),
            ],
        ),
    ]
