# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0016_irm_panelcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irm_panelcontact',
            name='Four_IRMLocationID_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irm_panelcontact_Fourth_Location', to='IRM.IRM_Location', verbose_name='IRM Location 4(optional)'),
        ),
        migrations.AlterField(
            model_name='irm_panelcontact',
            name='Principal_IRMLocationID_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irm_panelcontact_Principal_Location', to='IRM.IRM_Location', verbose_name='Principal IRM Location'),
        ),
        migrations.AlterField(
            model_name='irm_panelcontact',
            name='Three_IRMLocationID_FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irm_panelcontact_Third_Location', to='IRM.IRM_Location', verbose_name='IRM Location 3(optional)'),
        ),
        migrations.AlterField(
            model_name='irm_panelcontact',
            name='Two_IRMLocationID_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irm_panelcontact_Secondary_Location', to='IRM.IRM_Location', verbose_name='Secondary IRM Location'),
        ),
    ]
