# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0017_auto_20160411_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRM_PanelContactRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(help_text='Role', max_length=100)),
                ('ContactType', models.CharField(choices=[('Advisor', 'Advisor'), ('Member', 'Member')], help_text='Contact Type', max_length=20)),
            ],
        ),
    ]
