# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0018_irm_panelcontactrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irm_panelcontact',
            name='Panel_Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_PanelContactRole'),
        ),
    ]
