# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-12 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0019_auto_20160411_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRM_Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IRM_Reference', models.CharField(blank=True, max_length=20, null=True)),
                ('Date_Appliction_Received', models.DateField()),
                ('Inter_Country', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Major_Recommendation', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('Case_Notes', models.CharField(blank=True, max_length=100, null=True)),
                ('Salutation', models.CharField(blank=True, max_length=100, null=True)),
                ('Person_1_FirstName', models.CharField(max_length=100)),
                ('Person_1_Surname', models.CharField(max_length=100)),
                ('Person_1_Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('Person_1_DateOfBirth', models.DateField(blank=True, null=True)),
                ('Person_2_FirstName', models.CharField(blank=True, max_length=100, null=True)),
                ('Person_2_Surname', models.CharField(blank=True, max_length=100, null=True)),
                ('Person_2_Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('Person_2_DateOfBirth', models.DateField(blank=True, max_length=100, null=True)),
                ('Address_Line_1', models.CharField(max_length=100)),
                ('Address_Line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('Address_Line_3', models.CharField(blank=True, max_length=100, null=True)),
                ('Address_Line_4', models.CharField(blank=True, max_length=100, null=True)),
                ('Town', models.CharField(max_length=100)),
                ('County', models.CharField(blank=True, max_length=100, null=True)),
                ('Postcode', models.CharField(max_length=20)),
                ('Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Fax', models.CharField(blank=True, max_length=50, null=True)),
                ('ContactNotes', models.CharField(blank=True, max_length=2000, null=True)),
                ('Agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_Agency')),
                ('Agency_Decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IRM.Panel_Recommendations')),
                ('IRM_Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_Location')),
            ],
        ),
        migrations.AlterField(
            model_name='irm_panelcontact',
            name='Status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='irm_case',
            name='Legal_Advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.IRM_PanelContact'),
        ),
        migrations.AddField(
            model_name='irm_case',
            name='Marital_Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.Marital_Status'),
        ),
        migrations.AddField(
            model_name='irm_case',
            name='Person_1_Ethnicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irm_case_Person1_Ethnicity', to='IRM.IRM_Ethinicity'),
        ),
        migrations.AddField(
            model_name='irm_case',
            name='Person_1_Title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irm_case_Person1_Title', to='IRM.IRM_Title'),
        ),
        migrations.AddField(
            model_name='irm_case',
            name='Person_2_Ethnicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irm_case_Person2_Ethnicity', to='IRM.IRM_Ethinicity'),
        ),
        migrations.AddField(
            model_name='irm_case',
            name='Person_2_Title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irm_case_Person2_Title', to='IRM.IRM_Title'),
        ),
        migrations.AddField(
            model_name='irm_case',
            name='Report_Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IRM.Report_Status'),
        ),
        migrations.AddField(
            model_name='irm_case',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IRM.Case_Type'),
        ),
    ]
