# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0021_auto_20160412_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irm_case',
            name='Case_Notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='irm_case',
            name='ContactNotes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
