# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0022_auto_20160413_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='IRM_Case_dup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abc', models.CharField(blank=True, max_length=20, null=True)),
                ('lef', models.CharField(blank=True, max_length=20, null=True)),
                ('sar', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
