# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0023_irm_case_dup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency_TypeAudit',
            fields=[
                ('types', models.CharField(help_text='Type of Agency', max_length=100, verbose_name='Agency Type')),
                ('_audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('_audit_timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('_audit_change_type', models.CharField(max_length=1)),
                ('id', models.IntegerField(db_index=True, editable=False)),
            ],
            options={
                'ordering': ['-_audit_timestamp'],
                'db_table': 'IRM_agency_type_audit',
                'verbose_name_plural': 'agency_ type audit trail',
            },
        ),
    ]
