# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IRM', '0024_agency_typeaudit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agency_TypeAudit',
        ),
    ]
