# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30)),
                ('Date_of_Birth', models.DateField()),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'TransGender')], max_length=1)),
                ('Address_Line1', models.CharField(max_length=100)),
                ('Address_Line2', models.CharField(max_length=100)),
                ('Post_Code', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
            ],
        ),
    ]
