# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='E_Mail',
            field=models.EmailField(default='sharpsaran@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
