# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0002_person_e_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-modified', '-created']},
        ),
        migrations.AddField(
            model_name='person',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 2, 20, 32, 57, 794441, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 2, 20, 33, 2, 397414, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
