# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-02 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import form_wizard.models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0003_auto_20160402_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to=form_wizard.models.user_directory_path),
        ),
    ]
