# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_wizard', '0004_auto_20160402_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Council',
            field=models.CharField(default='london', max_length=100),
            preserve_default=False,
        ),
    ]
