# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DNS_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('A_Record', models.CharField(blank=True, max_length=100, null=True)),
                ('CName_Record', models.CharField(blank=True, max_length=100, null=True)),
                ('MX_Record', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_info_Created_By', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalDNS_Info',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('A_Record', models.CharField(blank=True, max_length=100, null=True)),
                ('CName_Record', models.CharField(blank=True, max_length=100, null=True)),
                ('MX_Record', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical dn s_ info',
            },
        ),
        migrations.CreateModel(
            name='HistoricalWebsite',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, editable=False)),
                ('modified_on', models.DateTimeField(blank=True, editable=False)),
                ('domain_name', models.CharField(max_length=100)),
                ('domain_provider', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('Hosting_server', models.CharField(blank=True, max_length=100, null=True)),
                ('hosting_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical website',
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=100)),
                ('domain_provider', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('Hosting_server', models.CharField(blank=True, max_length=100, null=True)),
                ('hosting_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('auto_renewal', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_Created_By', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-domain_name'],
            },
        ),
        migrations.AddField(
            model_name='historicaldns_info',
            name='domain_name',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='domain.Website'),
        ),
        migrations.AddField(
            model_name='historicaldns_info',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldns_info',
            name='modified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dns_info',
            name='domain_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_info_DNS_Info', to='domain.Website'),
        ),
        migrations.AddField(
            model_name='dns_info',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dns_info_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
