# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebsite',
            name='domain_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='website',
            name='domain_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
