# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIL1_Total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('TIL2_Total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('TIL1_Card', models.DecimalField(decimal_places=2, max_digits=20)),
                ('TIL1_Cash', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Grand_Total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Collection_Date', models.DateTimeField()),
                ('Updated_Dated', models.DateTimeField(auto_now_add=True)),
                ('Updated_User', models.CharField(max_length=200)),
                ('Active_Flag', models.BooleanField(default=True)),
                ('Bank_Deposit', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_Default_org', models.CharField(max_length=100)),
                ('user_URLField', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
