# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Retail_Report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
